---
directories:
  model_directory: './saved_models/depth_estimation_model'
  data_directory: './data/moon_yard'
  horizon_directory: './data/horizons'
  test_directory: './data/test_images'
image_parameters:
  image_height: 768
  image_width: 1024
...