---
dataset_parameters:
  root_folder: './data/moon_yard'
  masks_folder: './data/horizons'
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 4
  train_test_split: 0.75

experiment_parameters:
  learning_rate: 0.00001
  epochs: 10
  saved_model_dir: './saved_models/depth_estimation_model'
  pretrain: True
  
diode_parameters:
  root_folder: './data/diode'
  dataset_folder: './data/diode/val/outdoor'
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 4
  train_test_split: 0.75
  shuffle: True
  saved_model_dir: './saved_models/diode_depth_estimation_model'
  learning_rate: 0.00001
  epochs: 50
...