---
dataset_parameters:
  root_folder: './data/moon_yard'
  masks_folder: './data/horizons'
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 8
  train_test_split: 0.75

experiment_parameters:
  learning_rate: 0.00001
  epochs: 50
  saved_model_dir: './saved_models/moon_yard_model'
  checkpoint_file: './checkpoints/moon_yard/moon_yard_model-{epoch:02d}.ckpt'
  pretrain: True
  
diode_parameters:
  root_folder: './data/diode'
  train_folder: './data/diode/train/outdoor'
  val_folder: './data/diode/val/outdoor'
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 8
  shuffle: True
  saved_model_dir: './saved_models/diode_model'
  checkpoint_file: './checkpoints/diode/diode_model-{epoch:02d}.ckpt'
  learning_rate: 0.00001
  epochs: 100
...