---
dataset_parameters:
  root_folder: './data/moon_yard'
  masks_folder: './data/horizons'
  image_height: 1080
  image_width: 1920
  channels: 3
  batch_size: 4
  train_test_split: 0.75

experiment_parameters:
  learning_rate: 0.0002
  epochs: 30
...