---
directories:
  data_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\data'
  edges_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\edges'
  horizon_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\horizons'
  normalized_depth_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\normalized_depth'
  video_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\edges'
  image_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\terrain_classified_masks\inputs'
  segmentation_masks_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\terrain_classified_masks\masks'
  segmentation_predictions_directory: 'D:\PhD\depth_estimation\datasets\campaign_2\terrain_classified_masks\predictions'

filenames:
  video_file_name: 'edges_campaign_1.mp4'

flags:
  show_edges: False
  show_depth: False
  depth_from_point_cloud: False
  show_edges_from_segmentation: True

  show_images: False
  save_images: False
  
  draw_mask_flag: True

  create_video_flag: False
...