---
directories:
  data_directory: 'D:\\PhD\\Depth Estimation\\Analogue\\analogue_july12\\data'
  edges_directory: 'D:\\PhD\\Depth Estimation\\Analogue\\analogue_july12\\edges'
  horizon_directory: 'D:\\PhD\\Depth Estimation\\Analogue\\analogue_july12\\horizons'
  normalized_depth_directory: 'D:\\PhD\\Depth Estimation\\Analogue\\analogue_july12\\normalized_depth'

flags:
  detect_edges: False
  show_depth: True
  depth_from_point_cloud: False

  show_images: True
  save_images: False
  
  draw_mask_flag: False
...